const COMMENTS: Record<string, { up: string[]; down: string[] }> = {
  default: {
    up: [
      'Nice work.', 'Solid effort.', 'Well handled.', 'Coming along well.',
      'Consistent here.', 'Showing improvement.',
      'This is working.', 'Good awareness.', 'Progress is showing.',
      'Looking more comfortable.', 'Technique is there.', 'Keep it up.',
    ],
    down: [
      'Slow it down in practice to build consistency here.',
      'Focus on this one element at a time and it will come together.',
      'Great area to target — repetition will pay off quickly.',
      'Work through this slowly first, then bring it up to tempo.',
      'A little extra attention here will make a big difference.',
      'This is a great next step to work on.',
      'Drilling this in practice will unlock a lot.',
      'Break it down into smaller pieces and build it back up.',
      'This is very coachable — keep at it.',
      'Focusing on this in practice will show fast results.',
    ],
  },
  Posture: {
    up: [
      'Good posture.', 'Stays tall.', 'Clean body line.',
      'Strong and steady.', 'Well lifted.', 'Consistent shape.',
      'Grounded but upright.', 'Posture holds through the heat.',
      'Good length.', 'Reads well from a distance.',
      'Body line is clear.', 'Upright throughout.', 'Posture is a strength.',
    ],
    down: [
      'Think about growing taller through each step.',
      'Try practicing in front of a mirror to feel the lift.',
      'A small adjustment here will add a lot of presence.',
      'Focus on length through the top of the head.',
      'Keeping the torso more upright will open everything up.',
      'Imagine a string lifting from the crown — that\'s the feeling to chase.',
      'Great posture is just around the corner with a little focus.',
      'Head position is the key — keep working on steadying it.',
      'Staying lifted through transitions will make a big impact.',
      'Consistency here will really elevate the overall look.',
    ],
  },
  Footwork: {
    up: [
      'Clean footwork.', 'Good foot placement.', 'Steps are precise.',
      'Footwork is tidy.', 'Reliable underfoot.', 'Holds up at tempo.',
      'Good floor awareness.', 'Transitions are clean.',
      'Steps land clearly.', 'Footwork is a strength.',
      'Neat and deliberate.', 'Good control here.', 'Consistent steps.',
    ],
    down: [
      'Slow the tempo way down in practice — the details will come.',
      'Focus on one foot at a time and build from there.',
      'Deliberate, slow practice will pay off here quickly.',
      'Try marking through each step at half speed.',
      'The placement is close — just needs more repetition.',
      'This will click with consistent slow practice.',
      'Focus on where each foot lands before adding speed.',
      'Step by step — this is very much within reach.',
      'Break it into small sections and clean each one.',
      'Steady practice at a slower tempo will build this up fast.',
    ],
  },
  Timing: {
    up: [
      'Good timing.', 'Stays with the music.', 'Right on the beat.',
      'Rhythmically steady.', 'Doesn\'t rush or drag.', 'Tempo is consistent.',
      'Moves with the rhythm.', 'Timing is dependable.',
      'Catches the accents.', 'Stays on the music throughout.',
      'Timing is a strength.', 'Well-paced.', 'Musically reliable.',
    ],
    down: [
      'Try counting out loud in practice — it really helps.',
      'Focus on finding the pulse before adding footwork.',
      'Clapping the rhythm first will help it sink in.',
      'Listen for the first beat of each phrase and anchor to it.',
      'Slowing down to really feel the music will help.',
      'Try practicing with just the music, no steps, to reset.',
      'The timing is very coachable — focus on the beat.',
      'Practicing with a metronome will build confidence here.',
      'Find the pulse and let the steps follow it naturally.',
      'Settling into the rhythm earlier will help everything else fall into place.',
    ],
  },
  Connection: {
    up: [
      'Good connection.', 'Partners move as one.', 'Natural give-and-take.',
      'Reads as a partnership.', 'Responsive to each other.',
      'Communication is clear.', 'Comfortable together.',
      'Movement flows between partners.', 'Good awareness of each other.',
      'Neither partner forces it.', 'Partnership is settled.',
      'Connection is a strength.', 'Well attuned to each other.',
    ],
    down: [
      'Try softening the arms slightly to feel more of the partnership.',
      'Practice walking together slowly — it builds a lot of trust.',
      'Focus on listening before responding.',
      'Less effort, more listening — the connection will come.',
      'Awareness of each other will grow with more time together.',
      'Try matching breath with your partner in practice.',
      'Staying patient with each other is the key here.',
      'More practice time together will make this feel natural.',
      'Focus on the exchange rather than the steps.',
      'This kind of partnership takes time and will keep developing.',
    ],
  },
  Expression: {
    up: [
      'Good presence.', 'Natural expression.', 'Carries the character.',
      'Performance reads well.', 'Comfortable on the floor.',
      'Has personality.', 'Reads as a performer.',
      'Character comes through.', 'Stage presence is there.',
      'Dancing with intention.', 'Expression is growing.',
      'Nice variety.', 'The performance is there.',
    ],
    down: [
      'Think about what the dance means to you and let that show.',
      'Try picking one moment to really commit to the character.',
      'Expression grows naturally with comfort — keep performing.',
      'Focus on the feeling of the music and let it move through you.',
      'Performing for someone in the room will open this up.',
      'Think about the story the dance is telling.',
      'More stage time will bring this out naturally.',
      'Try adding one dynamic contrast to start.',
      'Expression is very much there — just let it out a little more.',
      'This is a great area to explore as confidence builds.',
    ],
  },
  Frame: {
    up: [
      'Good frame.', 'Frame holds well.', 'Consistent shape.',
      'Solid and stable.', 'Frame stays organized.', 'Doesn\'t waver.',
      'Active throughout.', 'Shape is clear.',
      'Steady under pressure.', 'Frame is a strength.',
      'Arms hold their position.', 'Well-structured.', 'Shape reads well.',
    ],
    down: [
      'Think of the frame as holding a shape, not just a position.',
      'Practicing frame in stillness first will help it hold in motion.',
      'Try isometric exercises to build frame stability.',
      'Focus on keeping the elbows lifted and supported.',
      'The frame will settle in with consistent practice.',
      'Work on it at the barre or in front of a mirror.',
      'A small amount of extra focus here will go a long way.',
      'Build it slowly — stillness first, then movement.',
      'Frame is very coachable — keep working on it.',
      'This is a great thing to drill for a few minutes each practice.',
    ],
  },
  'Leads & Follows': {
    up: [
      'Clear lead and follow.', 'Communication works.', 'In sync.',
      'Responses are timely.', 'Lead is clear.', 'Following is attentive.',
      'Cues are landing.', 'Neither partner forces it.',
      'Good balance between partners.', 'Following is responsive.',
      'Partnership communicates well.', 'Well matched.', 'Dynamic is working.',
    ],
    down: [
      'Leads: try making the intention clear a beat earlier.',
      'Followers: wait for the lead before responding — it will click.',
      'Slow down the leading and following in practice to feel the exchange.',
      'Try doing the pattern at walking pace with no music.',
      'More patience from both partners will help this develop.',
      'Focus on the give-and-take one move at a time.',
      'This kind of communication builds with practice — keep at it.',
      'Clearer initiation from the lead will help everything flow.',
      'Focusing on the connection point will help the cues land.',
      'This is very much a skill that comes with repetition together.',
    ],
  },
  Musicality: {
    up: [
      'Good musicality.', 'Moves with the music.', 'Interprets the music well.',
      'Musical instincts are good.', 'Responsive to the rhythm.',
      'Phrasing is there.', 'Sensitive to the music.',
      'Music guides the movement.', 'Comfortable with the structure.',
      'Movement and music connect.', 'Catches the dynamics.',
      'Musicality is a strength.', 'Good sense of phrase.',
    ],
    down: [
      'Try just listening to the music without dancing — find the phrases.',
      'Identify one musical accent to highlight per run-through.',
      'Let the music lead the movement rather than the steps.',
      'Focus on the dynamics — softer moments and stronger ones.',
      'Try singing along with the music as you dance.',
      'Notice where the phrase begins and ends — anchor there.',
      'Musicality grows with listening — spend time with the music.',
      'Try improvising to the music with no routine to feel it freely.',
      'This will open up as comfort with the steps grows.',
      'Responding to the music is a great next layer to develop.',
    ],
  },
}

// Deterministic pick: same inputs always produce the same comment
export function getComment(categoryName: string, sentiment: 'up' | 'down', studentId: number, heatId: number, categoryId: number): string {
  const list = (COMMENTS[categoryName] ?? COMMENTS.default)[sentiment]
  const seed = (studentId * 31 + heatId * 17 + categoryId * 7 + (sentiment === 'up' ? 0 : 1)) % list.length
  return list[Math.abs(seed)]
}
